### ISSUE TITLE
Can this device be used in conjunction with ACS712 sensor to measure CosFi?

### ISSUE THREAD

**Issue by jumpjack** [Abdurraziq/ZMPT101B-arduino#3]
Can these library and device be used also to measure phase difference between current and voltage, to measure CosFi, apparent power, active power,...?

**Comment by jumpjack** [comment]
up

**Comment by Abdurraziq** [comment]
Sorry @jumpjack, this library does not have a method to measure the voltage and current phase differences (cos phi). You might try the following [tutorial](https://learn.openenergymonitor.org/electricity-monitoring/ctac/how-to-build-an-arduino-energy-monitor) (note: this tutorial requires a CT sensor SCT-013-000 not ACS712)
