### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by mukulshrma25** [Abdurraziq/ZMPT101B-arduino#7]
These are the errors shown in the IDE:
1. 'ACS712_05B' was not declared in this scope
2. 'class ACS712' has no member named 'calibrate'
3. 'class ACS712' has no member named 'getCurrentAC'

**Comment by Abdurraziq** [comment]
hi @mukulshrma25. If you are trying to run the Wattmeter sample code make sure you have the [ACS712](https://github.com/rkoptev/ACS712-arduino) library installed. This error appears because you have not installed it.
